// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LrDb.Models
{
    public partial class Adobe_imageProofSettings
    {
        public long id_local { get; set; }
        public byte[] colorProfile { get; set; }
        public long? image { get; set; }
        public byte[] renderingIntent { get; set; }
    }
}