// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LrDb.Models
{
    public partial class Adobe_AdditionalMetadata
    {
        public long id_local { get; set; }
        public byte[] id_global { get; set; }
        public long additionalInfoSet { get; set; }
        public long embeddedXmp { get; set; }
        public long externalXmpIsDirty { get; set; }
        public long? image { get; set; }
        public long incrementalWhiteBalance { get; set; }
        public byte[] internalXmpDigest { get; set; }
        public long isRawFile { get; set; }
        public byte[] lastSynchronizedHash { get; set; }
        public byte[] lastSynchronizedTimestamp { get; set; }
        public byte[] metadataPresetID { get; set; }
        public byte[] metadataVersion { get; set; }
        public long monochrome { get; set; }
        public byte[] xmp { get; set; }
    }
}