// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LrDb.Models
{
    public partial class Adobe_imageDevelopSettings
    {
        public long id_local { get; set; }
        public long? allowFastRender { get; set; }
        public byte[] beforeSettingsIDCache { get; set; }
        public byte[] croppedHeight { get; set; }
        public byte[] croppedWidth { get; set; }
        public byte[] digest { get; set; }
        public byte[] fileHeight { get; set; }
        public byte[] fileWidth { get; set; }
        public long? grayscale { get; set; }
        public long hasBigData { get; set; }
        public long? hasDevelopAdjustments { get; set; }
        public byte[] hasDevelopAdjustmentsEx { get; set; }
        public byte[] historySettingsID { get; set; }
        public long? image { get; set; }
        public byte[] processVersion { get; set; }
        public byte[] profileCorrections { get; set; }
        public byte[] removeChromaticAberration { get; set; }
        public byte[] settingsID { get; set; }
        public byte[] snapshotID { get; set; }
        public byte[] text { get; set; }
        public byte[] validatedForVersion { get; set; }
        public byte[] whiteBalance { get; set; }
    }
}