// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LrDb.Models
{
    public partial class Adobe_libraryImageDevelopHistoryStep
    {
        public long id_local { get; set; }
        public byte[] id_global { get; set; }
        public byte[] dateCreated { get; set; }
        public byte[] digest { get; set; }
        public long hasBigData { get; set; }
        public byte[] hasDevelopAdjustments { get; set; }
        public long? image { get; set; }
        public byte[] name { get; set; }
        public byte[] relValueString { get; set; }
        public byte[] text { get; set; }
        public byte[] valueString { get; set; }
    }
}