// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LrDb.Models
{
    public partial class Adobe_libraryImageDevelop3DLUTColorTable
    {
        public long id_local { get; set; }
        public byte[] LUTFullString { get; set; }
        public byte[] LUTHash { get; set; }
    }
}