// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LrDb.Models
{
    public partial class Adobe_imageDevelopSettings
    {
        public long id_local { get; set; }
        public long? allowFastRender { get; set; }
        public double? beforeSettingsIDCache { get; set; }
        public string croppedHeight { get; set; }
        public string croppedWidth { get; set; }
        public string digest { get; set; }
        public double? fileHeight { get; set; }
        public double? fileWidth { get; set; }
        public long? grayscale { get; set; }
        public long hasBigData { get; set; }
        public long? hasDevelopAdjustments { get; set; }
        public long? hasDevelopAdjustmentsEx { get; set; }
        public string historySettingsID { get; set; }
        public long? image { get; set; }
        public string processVersion { get; set; }
        public double? profileCorrections { get; set; }
        public double? removeChromaticAberration { get; set; }
        public string settingsID { get; set; }
        public byte[] snapshotID { get; set; }
        public string text { get; set; }
        public double? validatedForVersion { get; set; }
        public string whiteBalance { get; set; }
    }
}