// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LrDb.Models
{
    public partial class Adobe_namedIdentityPlate
    {
        public long id_local { get; set; }
        public byte[] id_global { get; set; }
        public byte[] description { get; set; }
        public byte[] identityPlate { get; set; }
        public byte[] identityPlateHash { get; set; }
        public byte[] moduleFont { get; set; }
        public byte[] moduleSelectedTextColor { get; set; }
        public byte[] moduleTextColor { get; set; }
    }
}