// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LrDb.Models
{
    public partial class Adobe_imageDevelopBeforeSettings
    {
        public long id_local { get; set; }
        public byte[] beforeDigest { get; set; }
        public byte[] beforeHasDevelopAdjustments { get; set; }
        public byte[] beforePresetID { get; set; }
        public byte[] beforeText { get; set; }
        public long? developSettings { get; set; }
        public long hasBigData { get; set; }
    }
}