// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LrDb.Models
{
    public partial class Adobe_libraryImageFaceProcessHistory
    {
        public long id_local { get; set; }
        public long image { get; set; }
        public byte[] lastFaceDetector { get; set; }
        public byte[] lastFaceRecognizer { get; set; }
        public byte[] lastImageIndexer { get; set; }
        public byte[] lastImageOrientation { get; set; }
        public byte[] lastTryStatus { get; set; }
        public byte[] userTouched { get; set; }
    }
}