// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LrDb.Models
{
    public partial class AgDNGProxyInfo
    {
        public long id_local { get; set; }
        public byte[] fileUUID { get; set; }
        public byte[] status { get; set; }
        public byte[] statusDateTime { get; set; }
    }
}