// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LrDb.Models
{
    public partial class AgFolderContent
    {
        public long id_local { get; set; }
        public byte[] id_global { get; set; }
        public long containingFolder { get; set; }
        public byte[] content { get; set; }
        public byte[] name { get; set; }
        public byte[] owningModule { get; set; }
    }
}