// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LrDb.Models
{
    public partial class AgHarvestedIptcMetadata
    {
        public long id_local { get; set; }
        public long? image { get; set; }
        public long? cityRef { get; set; }
        public long? copyrightState { get; set; }
        public long? countryRef { get; set; }
        public long? creatorRef { get; set; }
        public long? isoCountryCodeRef { get; set; }
        public long? jobIdentifierRef { get; set; }
        public byte[] locationDataOrigination { get; set; }
        public byte[] locationGPSSequence { get; set; }
        public long? locationRef { get; set; }
        public long? stateRef { get; set; }
    }
}