// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LrDb.Models
{
    public partial class AgHarvestedDNGMetadata
    {
        public long id_local { get; set; }
        public long? image { get; set; }
        public long? hasFastLoadData { get; set; }
        public long? hasLossyCompression { get; set; }
        public long? isDNG { get; set; }
        public long? isHDR { get; set; }
        public long? isPano { get; set; }
        public long? isReducedResolution { get; set; }
    }
}