// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LrDb.Models
{
    public partial class AgInternedIptcCreator
    {
        public long id_local { get; set; }
        public byte[] searchIndex { get; set; }
        public byte[] value { get; set; }
    }
}