// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using LrDb.Utilities;

namespace LrDb.Models
{
    public partial class AgLibraryFile
    {
        public long id_local { get; set; }
        public Guid id_global { get; set; }
        public string baseName { get; set; }
        public byte[] errorMessage { get; set; }
        public byte[] errorTime { get; set; }
        public string extension { get; set; }
        public long externalModTime { get; set; }
        public long folder { get; set; }
        public string idx_filename { get; set; }
        public string importHash { get; set; }
        public string lc_idx_filename { get; set; }
        public string lc_idx_filenameExtension { get; set; }
        public byte[] md5 { get; set; }
        public long modTime { get; set; }
        public string originalFilename { get; set; }
        public string sidecarExtensions { get; set; }

        [NotMapped] public DateTime ModTimeStandard => ConversionHelpers.LrTimeStampToDateTime(modTime).ToLocalTime();
    }
}