// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LrDb.Models
{
    public partial class AgLibraryCollectionImageOzSortOrder
    {
        public byte[] collectionImage { get; set; }
        public byte[] collection { get; set; }
        public byte[] positionInCollection { get; set; }
        public byte[] ozSortOrder { get; set; }
    }
}