// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LrDb.Models
{
    public partial class AgLibraryFileAssetMetadata
    {
        public byte[] fileId { get; set; }
        public byte[] sha256 { get; set; }
        public byte[] fileSize { get; set; }
    }
}