// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LrDb.Models
{
    public partial class AgLibraryCollectionImage
    {
        public long id_local { get; set; }
        public long collection { get; set; }
        public long image { get; set; }
        public byte[] pick { get; set; }
        public byte[] positionInCollection { get; set; }
    }
}