// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LrDb.Models
{
    public partial class AgLibraryImageXMPUpdater
    {
        public long id_local { get; set; }
        public byte[] taskID { get; set; }
        public byte[] taskStatus { get; set; }
        public byte[] whenPosted { get; set; }
    }
}