// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LrDb.Models
{
    public partial class AgLibraryKeyword
    {
        public long id_local { get; set; }
        public byte[] id_global { get; set; }
        public byte[] dateCreated { get; set; }
        public byte[] genealogy { get; set; }
        public byte[] imageCountCache { get; set; }
        public long includeOnExport { get; set; }
        public long includeParents { get; set; }
        public long includeSynonyms { get; set; }
        public byte[] keywordType { get; set; }
        public byte[] lastApplied { get; set; }
        public byte[] lc_name { get; set; }
        public byte[] name { get; set; }
        public long? parent { get; set; }
    }
}