// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LrDb.Models
{
    public partial class AgLibraryFace
    {
        public long id_local { get; set; }
        public byte[] bl_x { get; set; }
        public byte[] bl_y { get; set; }
        public byte[] br_x { get; set; }
        public byte[] br_y { get; set; }
        public long? cluster { get; set; }
        public byte[] compatibleVersion { get; set; }
        public long? ignored { get; set; }
        public long image { get; set; }
        public byte[] imageOrientation { get; set; }
        public byte[] orientation { get; set; }
        public byte[] origination { get; set; }
        public byte[] propertiesCache { get; set; }
        public byte[] regionType { get; set; }
        public long? skipSuggestion { get; set; }
        public byte[] tl_x { get; set; }
        public byte[] tl_y { get; set; }
        public byte[] touchCount { get; set; }
        public byte[] touchTime { get; set; }
        public byte[] tr_x { get; set; }
        public byte[] tr_y { get; set; }
        public byte[] version { get; set; }
    }
}