// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LrDb.Models
{
    public partial class AgLibraryOzFeedbackInfo
    {
        public long id_local { get; set; }
        public byte[] image { get; set; }
        public byte[] lastFeedbackTime { get; set; }
        public byte[] lastReadTime { get; set; }
        public byte[] newCommentCount { get; set; }
        public byte[] newFavoriteCount { get; set; }
        public byte[] ozAssetId { get; set; }
        public byte[] ozCatalogId { get; set; }
        public byte[] ozSpaceId { get; set; }
    }
}