// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LrDb.Models
{
    public partial class AgLibraryCollectionLabel
    {
        public long id_local { get; set; }
        public byte[] id_global { get; set; }
        public long collection { get; set; }
        public byte[] label { get; set; }
        public byte[] labelData { get; set; }
        public byte[] labelGenerics { get; set; }
        public byte[] labelType { get; set; }
    }
}