// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LrDb.Models
{
    public partial class AgLibraryKeywordSynonym
    {
        public long id_local { get; set; }
        public long keyword { get; set; }
        public byte[] lc_name { get; set; }
        public byte[] name { get; set; }
    }
}