// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LrDb.Models
{
    public partial class AgLibraryFaceData
    {
        public long id_local { get; set; }
        public byte[] data { get; set; }
        public long face { get; set; }
    }
}