// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LrDb.Models
{
    public partial class AgLibraryImageSyncedAssetData
    {
        public byte[] image { get; set; }
        public byte[] payloadKey { get; set; }
        public byte[] payloadData { get; set; }
    }
}