// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LrDb.Models
{
    public partial class AgLibraryImport
    {
        public long id_local { get; set; }
        public byte[] imageCount { get; set; }
        public byte[] importDate { get; set; }
        public byte[] name { get; set; }
    }
}