// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LrDb.Models
{
    public partial class AgLibraryKeywordPopularity
    {
        public long id_local { get; set; }
        public byte[] occurrences { get; set; }
        public byte[] popularity { get; set; }
        public byte[] tag { get; set; }
    }
}