// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LrDb.Models
{
    public partial class AgLibraryIPTC
    {
        public long id_local { get; set; }
        public byte[] caption { get; set; }
        public byte[] copyright { get; set; }
        public long image { get; set; }
    }
}