// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LrDb.Models
{
    public partial class AgLibraryImageSearchData
    {
        public long id_local { get; set; }
        public byte[] featInfo { get; set; }
        public byte[] height { get; set; }
        public byte[] idDesc { get; set; }
        public byte[] idDescCh { get; set; }
        public long image { get; set; }
        public byte[] width { get; set; }
    }
}