// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LrDb.Models
{
    public partial class AgLibraryFolderStack
    {
        public long id_local { get; set; }
        public byte[] id_global { get; set; }
        public long collapsed { get; set; }
        public byte[] text { get; set; }
    }
}