// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LrDb.Models
{
    public partial class AgLibraryImageChangeCounter
    {
        public byte[] image { get; set; }
        public byte[] changeCounter { get; set; }
        public byte[] changedAtTime { get; set; }
        public byte[] localTimeOffsetSecs { get; set; }
    }
}