// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LrDb.Models
{
    public partial class AgLibraryOzCommentIds
    {
        public byte[] ozCatalogId { get; set; }
        public byte[] ozSpaceId { get; set; }
        public byte[] ozAssetId { get; set; }
        public byte[] ozCommentId { get; set; }
        public byte[] timestamp { get; set; }
    }
}