// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LrDb.Models
{
    public partial class AgMRULists
    {
        public long id_local { get; set; }
        public byte[] listID { get; set; }
        public byte[] timestamp { get; set; }
        public byte[] value { get; set; }
    }
}