// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LrDb.Models
{
    public partial class AgOutputImageAsset
    {
        public long id_local { get; set; }
        public byte[] assetId { get; set; }
        public long collection { get; set; }
        public long image { get; set; }
        public byte[] moduleId { get; set; }
    }
}