// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LrDb.Models
{
    public partial class AgPendingOzAlbumAssetIds
    {
        public byte[] ozCatalogId { get; set; }
        public byte[] ozAlbumAssetId { get; set; }
        public byte[] ozAssetId { get; set; }
        public byte[] ozAlbumId { get; set; }
        public byte[] ozSortOrder { get; set; }
        public byte[] ozIsCover { get; set; }
    }
}