// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LrDb.Models
{
    public partial class AgPendingOzAssetBinaryDownloads
    {
        public byte[] ozAssetId { get; set; }
        public byte[] ozCatalogId { get; set; }
        public byte[] whenQueued { get; set; }
        public byte[] path { get; set; }
        public byte[] state { get; set; }
    }
}