// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LrDb.Models
{
    public partial class AgPhotoPropertyArrayElement
    {
        public long id_local { get; set; }
        public byte[] id_global { get; set; }
        public byte[] arrayIndex { get; set; }
        public byte[] dataType { get; set; }
        public byte[] internalValue { get; set; }
        public long photo { get; set; }
        public long propertySpec { get; set; }
    }
}