// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LrDb.Models
{
    public partial class AgPhotoComment
    {
        public long id_local { get; set; }
        public byte[] id_global { get; set; }
        public byte[] comment { get; set; }
        public byte[] commentRealname { get; set; }
        public byte[] commentUsername { get; set; }
        public byte[] dateCreated { get; set; }
        public long photo { get; set; }
        public byte[] remoteId { get; set; }
        public long? remotePhoto { get; set; }
        public byte[] url { get; set; }
    }
}