// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LrDb.Models
{
    public partial class AgPhotoPropertySpec
    {
        public long id_local { get; set; }
        public byte[] id_global { get; set; }
        public byte[] flattenedAttributes { get; set; }
        public byte[] key { get; set; }
        public byte[] pluginVersion { get; set; }
        public byte[] sourcePlugin { get; set; }
        public byte[] userVisibleName { get; set; }
    }
}