// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LrDb.Models
{
    public partial class AgRemotePhoto
    {
        public long id_local { get; set; }
        public byte[] id_global { get; set; }
        public long collection { get; set; }
        public byte[] commentCount { get; set; }
        public byte[] developSettingsDigest { get; set; }
        public byte[] fileContentsHash { get; set; }
        public byte[] fileModTimestamp { get; set; }
        public byte[] metadataDigest { get; set; }
        public byte[] mostRecentCommentTime { get; set; }
        public byte[] orientation { get; set; }
        public long photo { get; set; }
        public byte[] photoNeedsUpdating { get; set; }
        public byte[] publishCount { get; set; }
        public byte[] remoteId { get; set; }
        public byte[] serviceAggregateRating { get; set; }
        public byte[] url { get; set; }
    }
}