// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LrDb.Models
{
    public partial class MigratedImages
    {
        public byte[] ozAssetId { get; set; }
        public byte[] ozCatalogId { get; set; }
        public long localId { get; set; }
    }
}