// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LrDb.Models
{
    public partial class MigratedCollectionImages
    {
        public byte[] ozAlbumId { get; set; }
        public byte[] ozAlbumAssetId { get; set; }
        public byte[] ozCatalogId { get; set; }
        public long localCollectionId { get; set; }
        public long localCollectionImageId { get; set; }
    }
}