// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LrDb.Models
{
    public partial class MigratedInfo
    {
        public string ozCatalogId { get; set; }
        public byte[] migrationStatus { get; set; }
        public byte[] timestamp { get; set; }
    }
}